version: '2'
services:
    calllogger-app:
        image: calllogger
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://calllogger-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=callLogger
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    calllogger-mongodb:
        extends:
            file: mongodb.yml
            service: calllogger-mongodb
